version: '3.8'

services:

  room-service:                                                                   # RoomService with PostgreSQL
    container_name: gbc_room-service
    build: ./room-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/room_service_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres-db
    networks:
      - backend

  postgres-db:                                                                   # Postgres DB
    container_name: gbc_postgres-db
    image: postgres:latest
    environment:
      POSTGRES_DB: room_service_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./init:/docker-entrypoint-initdb.d


  booking-service:                                                               # BookingService with MongoDB
    container_name: gbc_booking-service
    build: ./booking-service
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-db:27017/booking_service_db
    depends_on:
      - mongo-db
    networks:
      - backend

  mongo-db:                                                                       # MongoDb
    container_name: gbc_mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend

  mongo-express:                                                                  # Mongo Express
    container_name: gbc_mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMIN_USERNAME=admin
      - ME_CONFIG_MONGODB_ADMIN_PASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo-db
    depends_on:
      - mongo-db
    networks:
      - backend

  pgadmin:                                                                        # PGADMIN
    container_name: gbc_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"
    depends_on:
      - postgres-db
    networks:
      - backend



  user-service:                                                                 # UserService with PostgreSQL
    container_name: gbc_user-service
    build: ./user-service
    ports:
      - "8088:8088"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/user_service_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres-db
    networks:
      - backend


  event-service:                                                                # EventService with MongoDB
    container_name: gbc_event-service
    build: ./event-service
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo-db:27017/event_service_db
    depends_on:
      - mongo-db
    networks:
      - backend


  approval-service:                                                             # ApprovalService with PostgreSQL
    container_name: gbc_approval-service
    build: ./approval-service
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/approval_service_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres-db
    networks:
      - backend

networks:
  backend:
    driver: bridge